FROM oven/bun:latest

WORKDIR /usr/src/app

ENV HUSKY=0

COPY package.json ./
COPY apps/api/package.json ./apps/api/package.json
COPY bun.lock ./

RUN bun install

COPY apps/api ./apps/api
WORKDIR /app/apps/api

EXPOSE 3000/tcp
CMD [ "bun", "run", "index.ts" ]